{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=scheduled__2025-05-19T20:52:00+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:01:38.974+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T20:52:00+00:00 [queued]>\\n[2025-05-19T21:01:39.083+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T20:52:00+00:00 [queued]>\\n[2025-05-19T21:01:39.086+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:01:39.391+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 20:52:00+00:00\\n[2025-05-19T21:01:39.446+0000] {standard_task_runner.py:60} INFO - Started process 31751 to run task\\n[2025-05-19T21:01:39.501+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'scheduled__2025-05-19T20:52:00+00:00\\', \\'--job-id\\', \\'3\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmp5uofd26_\\']\\n[2025-05-19T21:01:39.603+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask fail_task_2\\n[2025-05-19T21:01:40.494+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:01:41.357+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T20:52:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:01:43.029+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notify_", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "scheduled__2025-05-19T20:52:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=manual__2025-05-19T21:01:36.159502+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:01:43.762+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 manual__2025-05-19T21:01:36.159502+00:00 [queued]>\\n[2025-05-19T21:01:43.814+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 manual__2025-05-19T21:01:36.159502+00:00 [queued]>\\n[2025-05-19T21:01:43.817+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:01:43.991+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 21:01:36.159502+00:00\\n[2025-05-19T21:01:44.052+0000] {standard_task_runner.py:60} INFO - Started process 31754 to run task\\n[2025-05-19T21:01:44.139+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'manual__2025-05-19T21:01:36.159502+00:00\\', \\'--job-id\\', \\'6\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmp7ekyc9nh\\']\\n[2025-05-19T21:01:44.213+0000] {standard_task_runner.py:88} INFO - Job 6: Subtask fail_task_2\\n[2025-05-19T21:01:44.447+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:01:44.854+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 manual__2025-05-19T21:01:36.159502+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:01:45.063+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DA", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "manual__2025-05-19T21:01:36.159502+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=scheduled__2025-05-19T20:57:00+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:02:01.579+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T20:57:00+00:00 [queued]>\\n[2025-05-19T21:02:01.623+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T20:57:00+00:00 [queued]>\\n[2025-05-19T21:02:01.632+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:02:01.684+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 20:57:00+00:00\\n[2025-05-19T21:02:01.703+0000] {standard_task_runner.py:60} INFO - Started process 31785 to run task\\n[2025-05-19T21:02:01.719+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'scheduled__2025-05-19T20:57:00+00:00\\', \\'--job-id\\', \\'9\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmprbn3uumf\\']\\n[2025-05-19T21:02:01.732+0000] {standard_task_runner.py:88} INFO - Job 9: Subtask fail_task_2\\n[2025-05-19T21:02:01.784+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:02:01.924+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T20:57:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:02:02.140+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notify_", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "scheduled__2025-05-19T20:57:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=scheduled__2025-05-19T21:02:00+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:07:07.453+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:02:00+00:00 [queued]>\\n[2025-05-19T21:07:07.475+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:02:00+00:00 [queued]>\\n[2025-05-19T21:07:07.477+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:07:07.517+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 21:02:00+00:00\\n[2025-05-19T21:07:07.543+0000] {standard_task_runner.py:60} INFO - Started process 32037 to run task\\n[2025-05-19T21:07:07.549+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'scheduled__2025-05-19T21:02:00+00:00\\', \\'--job-id\\', \\'15\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmpii65sxt6\\']\\n[2025-05-19T21:07:07.553+0000] {standard_task_runner.py:88} INFO - Job 15: Subtask fail_task_2\\n[2025-05-19T21:07:07.610+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:07:07.691+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:02:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:07:07.865+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "scheduled__2025-05-19T21:02:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=scheduled__2025-05-19T21:07:00+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:12:01.359+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:07:00+00:00 [queued]>\\n[2025-05-19T21:12:01.374+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:07:00+00:00 [queued]>\\n[2025-05-19T21:12:01.375+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:12:01.402+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 21:07:00+00:00\\n[2025-05-19T21:12:01.410+0000] {standard_task_runner.py:60} INFO - Started process 32282 to run task\\n[2025-05-19T21:12:01.416+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'scheduled__2025-05-19T21:07:00+00:00\\', \\'--job-id\\', \\'20\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmp5n40snf0\\']\\n[2025-05-19T21:12:01.420+0000] {standard_task_runner.py:88} INFO - Job 20: Subtask fail_task_2\\n[2025-05-19T21:12:01.451+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:12:01.506+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:07:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:12:01.662+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "scheduled__2025-05-19T21:07:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=scheduled__2025-05-19T21:12:00+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:17:07.075+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:12:00+00:00 [queued]>\\n[2025-05-19T21:17:07.098+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:12:00+00:00 [queued]>\\n[2025-05-19T21:17:07.099+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:17:07.153+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 21:12:00+00:00\\n[2025-05-19T21:17:07.170+0000] {standard_task_runner.py:60} INFO - Started process 32545 to run task\\n[2025-05-19T21:17:07.178+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'scheduled__2025-05-19T21:12:00+00:00\\', \\'--job-id\\', \\'24\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmpulwvmqga\\']\\n[2025-05-19T21:17:07.184+0000] {standard_task_runner.py:88} INFO - Job 24: Subtask fail_task_2\\n[2025-05-19T21:17:07.238+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:17:07.317+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:12:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:17:07.519+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "scheduled__2025-05-19T21:12:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=scheduled__2025-05-19T21:17:00+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:22:02.501+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:17:00+00:00 [queued]>\\n[2025-05-19T21:22:02.529+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:17:00+00:00 [queued]>\\n[2025-05-19T21:22:02.531+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:22:02.597+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 21:17:00+00:00\\n[2025-05-19T21:22:02.632+0000] {standard_task_runner.py:60} INFO - Started process 32843 to run task\\n[2025-05-19T21:22:02.640+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'scheduled__2025-05-19T21:17:00+00:00\\', \\'--job-id\\', \\'28\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmpji9phqsw\\']\\n[2025-05-19T21:22:02.647+0000] {standard_task_runner.py:88} INFO - Job 28: Subtask fail_task_2\\n[2025-05-19T21:22:02.734+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:22:02.890+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:17:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:22:03.247+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "scheduled__2025-05-19T21:17:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_2/run_id=scheduled__2025-05-19T21:22:00+00:00/task_id=fail_task_2/attempt=1.log\\n[2025-05-19T21:27:09.120+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:22:00+00:00 [queued]>\\n[2025-05-19T21:27:09.152+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:22:00+00:00 [queued]>\\n[2025-05-19T21:27:09.154+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:27:09.216+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_2> on 2025-05-19 21:22:00+00:00\\n[2025-05-19T21:27:09.234+0000] {standard_task_runner.py:60} INFO - Started process 33151 to run task\\n[2025-05-19T21:27:09.241+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_2\\', \\'fail_task_2\\', \\'scheduled__2025-05-19T21:22:00+00:00\\', \\'--job-id\\', \\'32\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_2.py\\', \\'--cfg-path\\', \\'/tmp/tmppqw3aouq\\']\\n[2025-05-19T21:27:09.248+0000] {standard_task_runner.py:88} INFO - Job 32: Subtask fail_task_2\\n[2025-05-19T21:27:09.308+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:27:09.408+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_2.fail_task_2 scheduled__2025-05-19T21:22:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:27:09.616+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_2", "task_id": "fail_task_2", "dag_run_id": "scheduled__2025-05-19T21:22:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_3/run_id=scheduled__2025-05-19T20:56:00+00:00/task_id=fail_task_3/attempt=1.log\\n[2025-05-19T21:01:38.974+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T20:56:00+00:00 [queued]>\\n[2025-05-19T21:01:39.083+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T20:56:00+00:00 [queued]>\\n[2025-05-19T21:01:39.085+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:01:39.392+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_3> on 2025-05-19 20:56:00+00:00\\n[2025-05-19T21:01:39.446+0000] {standard_task_runner.py:60} INFO - Started process 31750 to run task\\n[2025-05-19T21:01:39.479+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_3\\', \\'fail_task_3\\', \\'scheduled__2025-05-19T20:56:00+00:00\\', \\'--job-id\\', \\'5\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_3.py\\', \\'--cfg-path\\', \\'/tmp/tmp2nbs9fcv\\']\\n[2025-05-19T21:01:39.705+0000] {standard_task_runner.py:88} INFO - Job 5: Subtask fail_task_3\\n[2025-05-19T21:01:40.504+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:01:41.313+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T20:56:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:01:43.017+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notify_", "category": "generic", "dag_id": "demo_failure_notify_3", "task_id": "fail_task_3", "dag_run_id": "scheduled__2025-05-19T20:56:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_3/run_id=scheduled__2025-05-19T21:01:00+00:00/task_id=fail_task_3/attempt=1.log\\n[2025-05-19T21:06:02.931+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:01:00+00:00 [queued]>\\n[2025-05-19T21:06:02.956+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:01:00+00:00 [queued]>\\n[2025-05-19T21:06:02.958+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:06:02.998+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_3> on 2025-05-19 21:01:00+00:00\\n[2025-05-19T21:06:03.029+0000] {standard_task_runner.py:60} INFO - Started process 31975 to run task\\n[2025-05-19T21:06:03.037+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_3\\', \\'fail_task_3\\', \\'scheduled__2025-05-19T21:01:00+00:00\\', \\'--job-id\\', \\'14\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_3.py\\', \\'--cfg-path\\', \\'/tmp/tmpk252j3h3\\']\\n[2025-05-19T21:06:03.043+0000] {standard_task_runner.py:88} INFO - Job 14: Subtask fail_task_3\\n[2025-05-19T21:06:03.084+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:06:03.199+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:01:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:06:03.540+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_3", "task_id": "fail_task_3", "dag_run_id": "scheduled__2025-05-19T21:01:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_3/run_id=scheduled__2025-05-19T21:06:00+00:00/task_id=fail_task_3/attempt=1.log\\n[2025-05-19T21:11:03.734+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:06:00+00:00 [queued]>\\n[2025-05-19T21:11:03.761+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:06:00+00:00 [queued]>\\n[2025-05-19T21:11:03.763+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:11:03.802+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_3> on 2025-05-19 21:06:00+00:00\\n[2025-05-19T21:11:03.815+0000] {standard_task_runner.py:60} INFO - Started process 32235 to run task\\n[2025-05-19T21:11:03.823+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_3\\', \\'fail_task_3\\', \\'scheduled__2025-05-19T21:06:00+00:00\\', \\'--job-id\\', \\'19\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_3.py\\', \\'--cfg-path\\', \\'/tmp/tmp45h93i6i\\']\\n[2025-05-19T21:11:03.828+0000] {standard_task_runner.py:88} INFO - Job 19: Subtask fail_task_3\\n[2025-05-19T21:11:03.872+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:11:03.941+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:06:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:11:04.143+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_3", "task_id": "fail_task_3", "dag_run_id": "scheduled__2025-05-19T21:06:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_3/run_id=scheduled__2025-05-19T21:11:00+00:00/task_id=fail_task_3/attempt=1.log\\n[2025-05-19T21:16:03.346+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:11:00+00:00 [queued]>\\n[2025-05-19T21:16:03.371+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:11:00+00:00 [queued]>\\n[2025-05-19T21:16:03.373+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:16:03.416+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_3> on 2025-05-19 21:11:00+00:00\\n[2025-05-19T21:16:03.432+0000] {standard_task_runner.py:60} INFO - Started process 32483 to run task\\n[2025-05-19T21:16:03.438+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_3\\', \\'fail_task_3\\', \\'scheduled__2025-05-19T21:11:00+00:00\\', \\'--job-id\\', \\'23\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_3.py\\', \\'--cfg-path\\', \\'/tmp/tmpmxpyujid\\']\\n[2025-05-19T21:16:03.442+0000] {standard_task_runner.py:88} INFO - Job 23: Subtask fail_task_3\\n[2025-05-19T21:16:03.501+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:16:03.574+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:11:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:16:03.743+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_3", "task_id": "fail_task_3", "dag_run_id": "scheduled__2025-05-19T21:11:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_3/run_id=scheduled__2025-05-19T21:16:00+00:00/task_id=fail_task_3/attempt=1.log\\n[2025-05-19T21:21:04.948+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:16:00+00:00 [queued]>\\n[2025-05-19T21:21:04.984+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:16:00+00:00 [queued]>\\n[2025-05-19T21:21:04.985+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:21:05.055+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_3> on 2025-05-19 21:16:00+00:00\\n[2025-05-19T21:21:05.086+0000] {standard_task_runner.py:60} INFO - Started process 32784 to run task\\n[2025-05-19T21:21:05.094+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_3\\', \\'fail_task_3\\', \\'scheduled__2025-05-19T21:16:00+00:00\\', \\'--job-id\\', \\'27\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_3.py\\', \\'--cfg-path\\', \\'/tmp/tmpafq6hsxd\\']\\n[2025-05-19T21:21:05.103+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask fail_task_3\\n[2025-05-19T21:21:05.182+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:21:05.271+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:16:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:21:05.499+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_3", "task_id": "fail_task_3", "dag_run_id": "scheduled__2025-05-19T21:16:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_3/run_id=scheduled__2025-05-19T21:21:00+00:00/task_id=fail_task_3/attempt=1.log\\n[2025-05-19T21:26:03.283+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:21:00+00:00 [queued]>\\n[2025-05-19T21:26:03.309+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:21:00+00:00 [queued]>\\n[2025-05-19T21:26:03.310+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:26:03.355+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_3> on 2025-05-19 21:21:00+00:00\\n[2025-05-19T21:26:03.371+0000] {standard_task_runner.py:60} INFO - Started process 33079 to run task\\n[2025-05-19T21:26:03.378+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_3\\', \\'fail_task_3\\', \\'scheduled__2025-05-19T21:21:00+00:00\\', \\'--job-id\\', \\'31\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_3.py\\', \\'--cfg-path\\', \\'/tmp/tmppvwanfag\\']\\n[2025-05-19T21:26:03.382+0000] {standard_task_runner.py:88} INFO - Job 31: Subtask fail_task_3\\n[2025-05-19T21:26:03.447+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:26:03.517+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_3.fail_task_3 scheduled__2025-05-19T21:21:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:26:03.727+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_3", "task_id": "fail_task_3", "dag_run_id": "scheduled__2025-05-19T21:21:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_4/run_id=scheduled__2025-05-19T20:53:00+00:00/task_id=fail_task_4/attempt=1.log\\n[2025-05-19T21:01:38.974+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T20:53:00+00:00 [queued]>\\n[2025-05-19T21:01:39.080+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T20:53:00+00:00 [queued]>\\n[2025-05-19T21:01:39.085+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:01:39.406+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_4> on 2025-05-19 20:53:00+00:00\\n[2025-05-19T21:01:39.463+0000] {standard_task_runner.py:60} INFO - Started process 31752 to run task\\n[2025-05-19T21:01:39.516+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_4\\', \\'fail_task_4\\', \\'scheduled__2025-05-19T20:53:00+00:00\\', \\'--job-id\\', \\'2\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_4.py\\', \\'--cfg-path\\', \\'/tmp/tmpxlcy0m6h\\']\\n[2025-05-19T21:01:39.775+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask fail_task_4\\n[2025-05-19T21:01:40.592+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:01:41.768+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T20:53:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:01:42.938+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notify_", "category": "generic", "dag_id": "demo_failure_notify_4", "task_id": "fail_task_4", "dag_run_id": "scheduled__2025-05-19T20:53:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_4/run_id=scheduled__2025-05-19T20:58:00+00:00/task_id=fail_task_4/attempt=1.log\\n[2025-05-19T21:03:02.129+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T20:58:00+00:00 [queued]>\\n[2025-05-19T21:03:02.157+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T20:58:00+00:00 [queued]>\\n[2025-05-19T21:03:02.158+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:03:02.195+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_4> on 2025-05-19 20:58:00+00:00\\n[2025-05-19T21:03:02.210+0000] {standard_task_runner.py:60} INFO - Started process 31837 to run task\\n[2025-05-19T21:03:02.216+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_4\\', \\'fail_task_4\\', \\'scheduled__2025-05-19T20:58:00+00:00\\', \\'--job-id\\', \\'10\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_4.py\\', \\'--cfg-path\\', \\'/tmp/tmpzudzm3tm\\']\\n[2025-05-19T21:03:02.220+0000] {standard_task_runner.py:88} INFO - Job 10: Subtask fail_task_4\\n[2025-05-19T21:03:02.275+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:03:02.364+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T20:58:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:03:02.558+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_4", "task_id": "fail_task_4", "dag_run_id": "scheduled__2025-05-19T20:58:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_4/run_id=scheduled__2025-05-19T21:03:00+00:00/task_id=fail_task_4/attempt=1.log\\n[2025-05-19T21:08:02.136+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:03:00+00:00 [queued]>\\n[2025-05-19T21:08:02.163+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:03:00+00:00 [queued]>\\n[2025-05-19T21:08:02.165+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:08:02.210+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_4> on 2025-05-19 21:03:00+00:00\\n[2025-05-19T21:08:02.222+0000] {standard_task_runner.py:60} INFO - Started process 32079 to run task\\n[2025-05-19T21:08:02.227+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_4\\', \\'fail_task_4\\', \\'scheduled__2025-05-19T21:03:00+00:00\\', \\'--job-id\\', \\'16\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_4.py\\', \\'--cfg-path\\', \\'/tmp/tmpsoajxju7\\']\\n[2025-05-19T21:08:02.236+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask fail_task_4\\n[2025-05-19T21:08:02.308+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:08:02.394+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:03:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:08:02.573+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_4", "task_id": "fail_task_4", "dag_run_id": "scheduled__2025-05-19T21:03:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_4/run_id=scheduled__2025-05-19T21:08:00+00:00/task_id=fail_task_4/attempt=1.log\\n[2025-05-19T21:13:01.172+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:08:00+00:00 [queued]>\\n[2025-05-19T21:13:01.183+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:08:00+00:00 [queued]>\\n[2025-05-19T21:13:01.184+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:13:01.203+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_4> on 2025-05-19 21:08:00+00:00\\n[2025-05-19T21:13:01.214+0000] {standard_task_runner.py:60} INFO - Started process 32334 to run task\\n[2025-05-19T21:13:01.219+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_4\\', \\'fail_task_4\\', \\'scheduled__2025-05-19T21:08:00+00:00\\', \\'--job-id\\', \\'21\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_4.py\\', \\'--cfg-path\\', \\'/tmp/tmpkap96y9z\\']\\n[2025-05-19T21:13:01.222+0000] {standard_task_runner.py:88} INFO - Job 21: Subtask fail_task_4\\n[2025-05-19T21:13:01.247+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:13:01.303+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:08:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:13:01.411+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_4", "task_id": "fail_task_4", "dag_run_id": "scheduled__2025-05-19T21:08:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_4/run_id=scheduled__2025-05-19T21:13:00+00:00/task_id=fail_task_4/attempt=1.log\\n[2025-05-19T21:18:06.792+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:13:00+00:00 [queued]>\\n[2025-05-19T21:18:06.817+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:13:00+00:00 [queued]>\\n[2025-05-19T21:18:06.818+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:18:06.861+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_4> on 2025-05-19 21:13:00+00:00\\n[2025-05-19T21:18:06.886+0000] {standard_task_runner.py:60} INFO - Started process 32607 to run task\\n[2025-05-19T21:18:06.893+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_4\\', \\'fail_task_4\\', \\'scheduled__2025-05-19T21:13:00+00:00\\', \\'--job-id\\', \\'25\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_4.py\\', \\'--cfg-path\\', \\'/tmp/tmpp85bh9ks\\']\\n[2025-05-19T21:18:06.898+0000] {standard_task_runner.py:88} INFO - Job 25: Subtask fail_task_4\\n[2025-05-19T21:18:06.966+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:18:07.060+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:13:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:18:07.322+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_4", "task_id": "fail_task_4", "dag_run_id": "scheduled__2025-05-19T21:13:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_4/run_id=scheduled__2025-05-19T21:18:00+00:00/task_id=fail_task_4/attempt=1.log\\n[2025-05-19T21:23:03.704+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:18:00+00:00 [queued]>\\n[2025-05-19T21:23:03.764+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:18:00+00:00 [queued]>\\n[2025-05-19T21:23:03.767+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:23:03.834+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_4> on 2025-05-19 21:18:00+00:00\\n[2025-05-19T21:23:03.863+0000] {standard_task_runner.py:60} INFO - Started process 32905 to run task\\n[2025-05-19T21:23:03.926+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_4\\', \\'fail_task_4\\', \\'scheduled__2025-05-19T21:18:00+00:00\\', \\'--job-id\\', \\'29\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_4.py\\', \\'--cfg-path\\', \\'/tmp/tmpuurfuapt\\']\\n[2025-05-19T21:23:03.955+0000] {standard_task_runner.py:88} INFO - Job 29: Subtask fail_task_4\\n[2025-05-19T21:23:04.112+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:23:04.190+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:18:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:23:04.377+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_4", "task_id": "fail_task_4", "dag_run_id": "scheduled__2025-05-19T21:18:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_4/run_id=scheduled__2025-05-19T21:23:00+00:00/task_id=fail_task_4/attempt=1.log\\n[2025-05-19T21:28:01.933+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:23:00+00:00 [queued]>\\n[2025-05-19T21:28:01.956+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:23:00+00:00 [queued]>\\n[2025-05-19T21:28:01.957+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:28:01.993+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_4> on 2025-05-19 21:23:00+00:00\\n[2025-05-19T21:28:02.004+0000] {standard_task_runner.py:60} INFO - Started process 33193 to run task\\n[2025-05-19T21:28:02.011+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_4\\', \\'fail_task_4\\', \\'scheduled__2025-05-19T21:23:00+00:00\\', \\'--job-id\\', \\'33\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_4.py\\', \\'--cfg-path\\', \\'/tmp/tmpuf40cha5\\']\\n[2025-05-19T21:28:02.018+0000] {standard_task_runner.py:88} INFO - Job 33: Subtask fail_task_4\\n[2025-05-19T21:28:02.068+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:28:02.155+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_4.fail_task_4 scheduled__2025-05-19T21:23:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:28:02.338+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_4", "task_id": "fail_task_4", "dag_run_id": "scheduled__2025-05-19T21:23:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_5/run_id=scheduled__2025-05-19T20:54:00+00:00/task_id=fail_task_5/attempt=1.log\\n[2025-05-19T21:01:38.975+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T20:54:00+00:00 [queued]>\\n[2025-05-19T21:01:39.090+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T20:54:00+00:00 [queued]>\\n[2025-05-19T21:01:39.091+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:01:39.395+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_5> on 2025-05-19 20:54:00+00:00\\n[2025-05-19T21:01:39.579+0000] {standard_task_runner.py:60} INFO - Started process 31753 to run task\\n[2025-05-19T21:01:39.772+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_5\\', \\'fail_task_5\\', \\'scheduled__2025-05-19T20:54:00+00:00\\', \\'--job-id\\', \\'4\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_5.py\\', \\'--cfg-path\\', \\'/tmp/tmpmbsrfc1m\\']\\n[2025-05-19T21:01:39.788+0000] {standard_task_runner.py:88} INFO - Job 4: Subtask fail_task_5\\n[2025-05-19T21:01:40.493+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:01:41.421+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T20:54:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:01:42.988+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notify_", "category": "generic", "dag_id": "demo_failure_notify_5", "task_id": "fail_task_5", "dag_run_id": "scheduled__2025-05-19T20:54:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_5/run_id=scheduled__2025-05-19T20:59:00+00:00/task_id=fail_task_5/attempt=1.log\\n[2025-05-19T21:04:02.567+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T20:59:00+00:00 [queued]>\\n[2025-05-19T21:04:02.685+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T20:59:00+00:00 [queued]>\\n[2025-05-19T21:04:02.745+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:04:02.839+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_5> on 2025-05-19 20:59:00+00:00\\n[2025-05-19T21:04:02.862+0000] {standard_task_runner.py:60} INFO - Started process 31891 to run task\\n[2025-05-19T21:04:02.872+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_5\\', \\'fail_task_5\\', \\'scheduled__2025-05-19T20:59:00+00:00\\', \\'--job-id\\', \\'12\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_5.py\\', \\'--cfg-path\\', \\'/tmp/tmpvlxh9_57\\']\\n[2025-05-19T21:04:02.880+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask fail_task_5\\n[2025-05-19T21:04:02.964+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:04:03.073+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T20:59:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:04:03.281+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_5", "task_id": "fail_task_5", "dag_run_id": "scheduled__2025-05-19T20:59:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_5/run_id=scheduled__2025-05-19T21:04:00+00:00/task_id=fail_task_5/attempt=1.log\\n[2025-05-19T21:09:04.956+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:04:00+00:00 [queued]>\\n[2025-05-19T21:09:05.010+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:04:00+00:00 [queued]>\\n[2025-05-19T21:09:05.012+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:09:05.119+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_5> on 2025-05-19 21:04:00+00:00\\n[2025-05-19T21:09:05.135+0000] {standard_task_runner.py:60} INFO - Started process 32133 to run task\\n[2025-05-19T21:09:05.142+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_5\\', \\'fail_task_5\\', \\'scheduled__2025-05-19T21:04:00+00:00\\', \\'--job-id\\', \\'18\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_5.py\\', \\'--cfg-path\\', \\'/tmp/tmp9d9zrpos\\']\\n[2025-05-19T21:09:05.147+0000] {standard_task_runner.py:88} INFO - Job 18: Subtask fail_task_5\\n[2025-05-19T21:09:05.217+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:09:05.283+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:04:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:09:05.502+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_5", "task_id": "fail_task_5", "dag_run_id": "scheduled__2025-05-19T21:04:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_5/run_id=scheduled__2025-05-19T21:09:00+00:00/task_id=fail_task_5/attempt=1.log\\n[2025-05-19T21:14:03.246+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:09:00+00:00 [queued]>\\n[2025-05-19T21:14:03.283+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:09:00+00:00 [queued]>\\n[2025-05-19T21:14:03.288+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:14:03.352+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_5> on 2025-05-19 21:09:00+00:00\\n[2025-05-19T21:14:03.362+0000] {standard_task_runner.py:60} INFO - Started process 32386 to run task\\n[2025-05-19T21:14:03.370+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_5\\', \\'fail_task_5\\', \\'scheduled__2025-05-19T21:09:00+00:00\\', \\'--job-id\\', \\'22\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_5.py\\', \\'--cfg-path\\', \\'/tmp/tmpl6ky0aui\\']\\n[2025-05-19T21:14:03.376+0000] {standard_task_runner.py:88} INFO - Job 22: Subtask fail_task_5\\n[2025-05-19T21:14:03.818+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:14:04.061+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:09:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:14:04.647+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_5", "task_id": "fail_task_5", "dag_run_id": "scheduled__2025-05-19T21:09:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_5/run_id=scheduled__2025-05-19T21:14:00+00:00/task_id=fail_task_5/attempt=1.log\\n[2025-05-19T21:19:03.532+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:14:00+00:00 [queued]>\\n[2025-05-19T21:19:03.564+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:14:00+00:00 [queued]>\\n[2025-05-19T21:19:03.566+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:19:03.610+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_5> on 2025-05-19 21:14:00+00:00\\n[2025-05-19T21:19:03.622+0000] {standard_task_runner.py:60} INFO - Started process 32664 to run task\\n[2025-05-19T21:19:03.630+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_5\\', \\'fail_task_5\\', \\'scheduled__2025-05-19T21:14:00+00:00\\', \\'--job-id\\', \\'26\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_5.py\\', \\'--cfg-path\\', \\'/tmp/tmpovr3lba7\\']\\n[2025-05-19T21:19:03.635+0000] {standard_task_runner.py:88} INFO - Job 26: Subtask fail_task_5\\n[2025-05-19T21:19:03.698+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:19:03.816+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:14:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:19:04.403+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_5", "task_id": "fail_task_5", "dag_run_id": "scheduled__2025-05-19T21:14:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_5/run_id=scheduled__2025-05-19T21:19:00+00:00/task_id=fail_task_5/attempt=1.log\\n[2025-05-19T21:24:01.061+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:19:00+00:00 [queued]>\\n[2025-05-19T21:24:01.080+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:19:00+00:00 [queued]>\\n[2025-05-19T21:24:01.082+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:24:01.111+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_5> on 2025-05-19 21:19:00+00:00\\n[2025-05-19T21:24:01.121+0000] {standard_task_runner.py:60} INFO - Started process 32962 to run task\\n[2025-05-19T21:24:01.127+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_5\\', \\'fail_task_5\\', \\'scheduled__2025-05-19T21:19:00+00:00\\', \\'--job-id\\', \\'30\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_5.py\\', \\'--cfg-path\\', \\'/tmp/tmp2zwd8tbq\\']\\n[2025-05-19T21:24:01.132+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask fail_task_5\\n[2025-05-19T21:24:01.177+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:24:01.272+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:19:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:24:01.475+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_5", "task_id": "fail_task_5", "dag_run_id": "scheduled__2025-05-19T21:19:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=demo_failure_notify_5/run_id=scheduled__2025-05-19T21:24:00+00:00/task_id=fail_task_5/attempt=1.log\\n[2025-05-19T21:29:01.265+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:24:00+00:00 [queued]>\\n[2025-05-19T21:29:01.306+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:24:00+00:00 [queued]>\\n[2025-05-19T21:29:01.308+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:29:01.358+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fail_task_5> on 2025-05-19 21:24:00+00:00\\n[2025-05-19T21:29:01.405+0000] {standard_task_runner.py:60} INFO - Started process 33255 to run task\\n[2025-05-19T21:29:01.412+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'demo_failure_notify_5\\', \\'fail_task_5\\', \\'scheduled__2025-05-19T21:24:00+00:00\\', \\'--job-id\\', \\'34\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_5.py\\', \\'--cfg-path\\', \\'/tmp/tmpu8q5shho\\']\\n[2025-05-19T21:29:01.419+0000] {standard_task_runner.py:88} INFO - Job 34: Subtask fail_task_5\\n[2025-05-19T21:29:01.455+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:29:01.563+0000] {task_command.py:423} INFO - Running <TaskInstance: demo_failure_notify_5.fail_task_5 scheduled__2025-05-19T21:24:00+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:29:01.796+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=\\'demo_failure_notif", "category": "generic", "dag_id": "demo_failure_notify_5", "task_id": "fail_task_5", "dag_run_id": "scheduled__2025-05-19T21:24:00+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=failure_notify_dag_1/run_id=manual__2025-05-19T21:01:44.982704+00:00/task_id=failing_task/attempt=1.log\\n[2025-05-19T21:01:50.537+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: failure_notify_dag_1.failing_task manual__2025-05-19T21:01:44.982704+00:00 [queued]>\\n[2025-05-19T21:01:50.554+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: failure_notify_dag_1.failing_task manual__2025-05-19T21:01:44.982704+00:00 [queued]>\\n[2025-05-19T21:01:50.556+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 4\\n[2025-05-19T21:01:50.597+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): failing_task> on 2025-05-19 21:01:44.982704+00:00\\n[2025-05-19T21:01:50.617+0000] {standard_task_runner.py:60} INFO - Started process 31763 to run task\\n[2025-05-19T21:01:50.623+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'failure_notify_dag_1\\', \\'failing_task\\', \\'manual__2025-05-19T21:01:44.982704+00:00\\', \\'--job-id\\', \\'8\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_notify_dag_1.py\\', \\'--cfg-path\\', \\'/tmp/tmpgg0hfavx\\']\\n[2025-05-19T21:01:50.627+0000] {standard_task_runner.py:88} INFO - Job 8: Subtask failing_task\\n[2025-05-19T21:01:50.649+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:01:50.702+0000] {task_command.py:423} INFO - Running <TaskInstance: failure_notify_dag_1.failing_task manual__2025-05-19T21:01:44.982704+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:01:50.817+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_", "category": "generic", "dag_id": "failure_notify_dag_1", "task_id": "failing_task", "dag_run_id": "manual__2025-05-19T21:01:44.982704+00:00", "source": "airflow"}
{"log_excerpt": "[('', \"*** Could not read served logs: Request URL is missing an 'http://' or 'https://' protocol.\\n\")]", "category": "generic", "dag_id": "failure_notify_dag_1", "task_id": "log_issue_url", "dag_run_id": "manual__2025-05-19T21:01:44.982704+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', \"*** Found local files:\\n***   * /opt/airflow/logs/dag_id=failure_notify_dag_1/run_id=manual__2025-05-19T21:01:44.982704+00:00/task_id=route_task/attempt=1.log\\n[2025-05-19T21:01:48.154+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: failure_notify_dag_1.route_task manual__2025-05-19T21:01:44.982704+00:00 [queued]>\\n[2025-05-19T21:01:48.182+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: failure_notify_dag_1.route_task manual__2025-05-19T21:01:44.982704+00:00 [queued]>\\n[2025-05-19T21:01:48.184+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:01:48.223+0000] {taskinstance.py:2191} INFO - Executing <Task(BranchPythonOperator): route_task> on 2025-05-19 21:01:44.982704+00:00\\n[2025-05-19T21:01:48.243+0000] {standard_task_runner.py:60} INFO - Started process 31761 to run task\\n[2025-05-19T21:01:48.250+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'failure_notify_dag_1', 'route_task', 'manual__2025-05-19T21:01:44.982704+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/failure_notify_dag_1.py', '--cfg-path', '/tmp/tmpe3nwcva4']\\n[2025-05-19T21:01:48.259+0000] {standard_task_runner.py:88} INFO - Job 7: Subtask route_task\\n[2025-05-19T21:01:48.291+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:01:48.371+0000] {task_command.py:423} INFO - Running <TaskInstance: failure_notify_dag_1.route_task manual__2025-05-19T21:01:44.982704+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:01:48.559+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='failure_notify_dag_1' AIRFLO", "category": "generic", "dag_id": "failure_notify_dag_1", "task_id": "route_task", "dag_run_id": "manual__2025-05-19T21:01:44.982704+00:00", "source": "airflow"}
{"log_excerpt": "[('', \"*** Could not read served logs: Request URL is missing an 'http://' or 'https://' protocol.\\n\")]", "category": "generic", "dag_id": "failure_simulation_dag", "task_id": "task_end", "dag_run_id": "manual__2025-05-19T21:30:06.786342+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', \"*** Found local files:\\n***   * /opt/airflow/logs/dag_id=failure_simulation_dag/run_id=manual__2025-05-19T21:30:06.786342+00:00/task_id=task_start/attempt=1.log\\n[2025-05-19T21:30:11.184+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: failure_simulation_dag.task_start manual__2025-05-19T21:30:06.786342+00:00 [queued]>\\n[2025-05-19T21:30:11.213+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: failure_simulation_dag.task_start manual__2025-05-19T21:30:06.786342+00:00 [queued]>\\n[2025-05-19T21:30:11.215+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:30:11.253+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task_start> on 2025-05-19 21:30:06.786342+00:00\\n[2025-05-19T21:30:11.269+0000] {standard_task_runner.py:60} INFO - Started process 33327 to run task\\n[2025-05-19T21:30:11.277+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'failure_simulation_dag', 'task_start', 'manual__2025-05-19T21:30:06.786342+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/failure_simulation_dag.py', '--cfg-path', '/tmp/tmpxu7uq333']\\n[2025-05-19T21:30:11.283+0000] {standard_task_runner.py:88} INFO - Job 35: Subtask task_start\\n[2025-05-19T21:30:11.333+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:30:11.422+0000] {task_command.py:423} INFO - Running <TaskInstance: failure_simulation_dag.task_start manual__2025-05-19T21:30:06.786342+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:30:11.687+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='failure_simulation_d", "category": "generic", "dag_id": "failure_simulation_dag", "task_id": "task_start", "dag_run_id": "manual__2025-05-19T21:30:06.786342+00:00", "source": "airflow"}
{"log_excerpt": "[('87e49f29cb9e', '*** Found local files:\\n***   * /opt/airflow/logs/dag_id=failure_simulation_dag/run_id=manual__2025-05-19T21:30:06.786342+00:00/task_id=task_fail/attempt=1.log\\n[2025-05-19T21:30:13.565+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: failure_simulation_dag.task_fail manual__2025-05-19T21:30:06.786342+00:00 [queued]>\\n[2025-05-19T21:30:13.589+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: failure_simulation_dag.task_fail manual__2025-05-19T21:30:06.786342+00:00 [queued]>\\n[2025-05-19T21:30:13.591+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1\\n[2025-05-19T21:30:13.620+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): task_fail> on 2025-05-19 21:30:06.786342+00:00\\n[2025-05-19T21:30:13.630+0000] {standard_task_runner.py:60} INFO - Started process 33334 to run task\\n[2025-05-19T21:30:13.638+0000] {standard_task_runner.py:87} INFO - Running: [\\'***\\', \\'tasks\\', \\'run\\', \\'failure_simulation_dag\\', \\'task_fail\\', \\'manual__2025-05-19T21:30:06.786342+00:00\\', \\'--job-id\\', \\'36\\', \\'--raw\\', \\'--subdir\\', \\'DAGS_FOLDER/failure_simulation_dag.py\\', \\'--cfg-path\\', \\'/tmp/tmp4fbt4k31\\']\\n[2025-05-19T21:30:13.643+0000] {standard_task_runner.py:88} INFO - Job 36: Subtask task_fail\\n[2025-05-19T21:30:13.691+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.\\n[2025-05-19T21:30:13.782+0000] {task_command.py:423} INFO - Running <TaskInstance: failure_simulation_dag.task_fail manual__2025-05-19T21:30:06.786342+00:00 [running]> on host 87e49f29cb9e\\n[2025-05-19T21:30:13.981+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER=\\'***\\' AIRFLOW_CTX_DAG_ID=", "category": "generic", "dag_id": "failure_simulation_dag", "task_id": "task_fail", "dag_run_id": "manual__2025-05-19T21:30:06.786342+00:00", "source": "airflow"}
